### ISSUE TITLE
why is the quanti-aware training very slow?

### ISSUE THREAD

**Issue by brisker** [openvinotoolkit/nncf_pytorch#128]
why is the quanti-aware training very slow?(almost 2 times slower than float model training). Is there any way to speed up the quanti-aware training?

**Comment by vshampor** [comment]
@brisker, in part it is so because every tensor that is quantized has an overhead of quantization simulation at every forward, and an overhead of calculating gradients for the trainable quantization parameters. This overhead is for each element of each quantized tensor, be it activations or weights. We already provide CUDA kernels for both forward and backward quantization computations so that the slowdown is alleviated somewhat:
https://github.com/openvinotoolkit/nncf_pytorch/tree/develop/nncf/extensions

You may try taking a look at the kernels and if you spot a lack of optimization somewhere, please let us know.
