### ISSUE TITLE
Missing Nodes & Edges in NNCF Graph for EfficientNet-B0

### ISSUE THREAD

**Issue by vuiseng9** [openvinotoolkit/nncf_pytorch#208]
NNCF is amazing! XD 

We could easily wrap EfficientB0 with NNCF to quantize to Int8 with decent accuracy. 

However, upon reviewing the original_graph.png and compressed_graph.png. There are missing connections between the nodes. Please see attached files.

The Swish activation layers seem to be missing, the swish layer is wrapped as torch.jit.script module. how should we handle this? The current case is skipping many activations which have to be quantized.

To reproduce the issue, do the following in the NNCF-enabled environment, no additional installation required.
1. clone https://github.com/vuiseng9/gen-efficientnet-pytorch (fork of [gen-efficientnet-pytorch](https://github.com/rwightman/gen-efficientnet-pytorch))
2. checkout branch: ```nncf-quantize```
3. run ```run_nncf_efficientnet_b0_int8.sh``` (do revise the dataset path)

[efficientnet-b0-torchmodule.txt](https://github.com/openvinotoolkit/nncf_pytorch/files/5408008/efficientnet-b0-torchmodule.txt)
![original_graph](https://user-images.githubusercontent.com/15026897/96573241-6d52c200-1300-11eb-92e7-feea9897e1ab.png)
![compressed_graph](https://user-images.githubusercontent.com/15026897/96573228-6926a480-1300-11eb-841e-0bff26bcd4b2.png)

**Comment by vshampor** [comment]
Greetings, VS!

I suppose you could use `@register_operator` decorator to mark the swish operation to be treated in NNCF as atomic and to be traced in the graph. For an example, see examples/common/models/classification/mobilenetv3.py:58

Not sure, however, what the correct order of the decorators should be for everything to work with the JIT case. Probably `@register_operator` should come first.

Alternatively, you may have to modify the model code so that it does not use JIT - should be pretty straightforward, and the repo seems to already have the corresponding functions anyway. You may also have to use `@register_operator` in this case as well, if you do not want the swish sub-operations to appear in the graph and instead for the swish to show up as a single node.
